[package]
name = "mwa_hyperdrive_core"
version = "0.1.0"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[features]
default = ["beam"]
beam = ["mwa_hyperbeam", "dashmap"]
erfa-static = ["erfa-sys/static"]
hdf5-static = ["mwa_hyperbeam/hdf5-static"]
all-static = ["erfa-static", "hdf5-static"]

[dependencies]
approx = { version = "0.4.*", features = ["num-complex"] }
erfa-sys = "0.1.*"
log = "0.4.*"
num = "0.3.*"
rayon = ">=1.3,<1.6"
serde = { version = "1.0.*", features = ["derive"] }
thiserror = "1.0.*"

# mwalib = { git = "https://github.com/MWATelescope/mwalib", tag = "v0.4.4" }
mwalib = { path = "/home/chj/Software/personal/mwalib" }

dashmap = { version = "4.0.*", optional = true }
mwa_hyperbeam = { version = "0.3.*", optional = true }

[dev-dependencies]
ndarray = { version = ">=0.13,<0.16", features = ["approx"] }
serial_test = "0.5.*"
