[package]
name = "mwa_hyperdrive_core"
version = "0.1.0"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
erfa-static = ["erfa-sys/static"]

[build-dependencies]
bindgen = "0.55.*"
pkg-config = "0.3.*"

[dev-dependencies]
approx = "0.4.*"

[dependencies]
erfa-sys = "0.1.*"
log = "0.4.*"
num = "0.3.*"
rayon = "1.4.*"
serde = { version = "1.0.*", features = ["derive"] }
thiserror = "1.0.*"

mwalib = { git = "https://github.com/MWATelescope/mwalib", tag = "v0.4.2" }
