[package]
name = "mwa_hyperdrive_beam"
version = "0.0.0"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2021"
license = "MPL-2.0"

[features]
hdf5-static = ["mwa_hyperbeam/hdf5-static"]
cuda = ["mwa_hyperbeam/cuda", "mwa_hyperdrive_common/cuda"]
cuda-single = ["cuda", "mwa_hyperbeam/cuda-single"]

[dependencies]
mwa_hyperbeam = "0.4.0"

mwa_hyperdrive_common =  { path = "../common" }

[dev-dependencies]
approx = "0.5.0"
ndarray = { version = ">=0.15.4,<0.16", features = ["approx-0_5"] }
serial_test = "0.5.0"
