[package]
name = "mwa_hyperdrive_srclist"
version = "0.1.0"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.*"
fern = "0.6.*"
lazy_static = "1.4.*"
log = "0.4.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
serde_yaml = "0.8.*"
structopt = "0.3.*"
strum = "0.19.*"
strum_macros = "0.19.*"
thiserror = "1.0.*"

mwa_hyperdrive_core = { path = "../core" }

[dev-dependencies]
approx = "0.4.*"
indoc = "1.0.*"
tempfile = "3.1.0"
