[package]
name = "mwa_hyperdrive_cuda"
version = "0.1.0"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
cuda-runtime-sys = "0.3.0-alpha.1"

[build-dependencies]
cc = { version = "1.0.*", features = ["parallel"] }
