/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    #[doc = " A \"watered-down\" version of the CUDA example \"deviceQuery\".\n\n See the full example at:\nhttps://github.com/NVIDIA/cuda-samples/blob/master/Samples/1_Utilities/deviceQuery/deviceQuery.cpp\n\n As this code contains code derived from an official NVIDIA example, legally,\n a copyright, list of conditions and disclaimer must be distributed with this\n code. This should be found in the root of the mwa_hyperdrive git repo, file\n LICENSE-NVIDIA."]
    pub fn get_gpu_device_info(
        device: ::std::os::raw::c_int,
        name: *mut ::std::os::raw::c_char,
        device_major: *mut ::std::os::raw::c_int,
        device_minor: *mut ::std::os::raw::c_int,
        total_global_mem: *mut usize,
        driver_version: *mut ::std::os::raw::c_int,
        runtime_version: *mut ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Zero the beam-response Jones matrices of every direction below the horizon.\n\n `d_jones` has shape (`num_tiles`, `num_freqs`, `num_directions`), slowest to\n fastest (the layout hyperbeam's GPU beam code writes), and `d_zas` holds\n `num_directions` zenith angles [radians]. Both are in the GPU precision\n (`float` with `SINGLE`, otherwise `double`), so each Jones matrix is 8\n floats; they are passed as `void` pointers so that this declaration is the\n same for both precisions. A direction is below the horizon if its zenith\n angle is greater than pi/2."]
    pub fn zero_jones_below_horizon(
        d_zas: *const ::std::os::raw::c_void,
        num_directions: ::std::os::raw::c_int,
        num_tiles: ::std::os::raw::c_int,
        num_freqs: ::std::os::raw::c_int,
        d_jones: *mut ::std::os::raw::c_void,
    ) -> *const ::std::os::raw::c_char;
}
