---
name: Generate Coverage report

on:
  push:
    branches:
      - "**" # run on every branch push...
    tags-ignore:
      - "**" # ...but don't double up on tags
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -C target-cpu=native

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            tzdata \
            build-essential \
            pkg-config \
            cmake \
            curl \
            git \
            gpg \
            lcov \
            libcfitsio-dev \
            libhdf5-dev \
            libfreetype-dev \
            libexpat1-dev \
            libfontconfig-dev \
            ;
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      # https://lib.rs/crates/cargo-llvm-cov#readme-continuous-integration
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Cache MWA beam file
        id: cache-beam
        uses: actions/cache@v5
        with:
          path: mwa_full_embedded_element_pattern.h5
          key: mwa-beam-file-v1

      - name: Download MWA beam file if cache was a miss
        if: steps.cache-beam.outputs.cache-hit != 'true'
        run: |
          curl -fL \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            --retry 5 \
            --retry-delay 10 \
            --retry-all-errors \
            --retry-max-time 120 \
            https://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 \
            -o mwa_full_embedded_element_pattern.h5

      - name: Generate test lcov coverage into coverage/ dir
        run: |
          export MWA_BEAM_FILE=$(realpath mwa_full_embedded_element_pattern.h5)
          cargo llvm-cov --workspace --release --lcov --output-path lcov.info

      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v6
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
