---
name: Generate Coverage report

on:
  push:
    tags-ignore:
      - '**'
    pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            tzdata \
            build-essential \
            pkg-config \
            cmake \
            curl \
            git \
            lcov \
            libcfitsio-dev \
            libhdf5-dev \
            libfreetype-dev \
            libexpat1-dev \
            ;
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      # https://lib.rs/crates/cargo-llvm-cov#readme-continuous-integration
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Get the beam HDF5 file
        run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

      - name: Generate test lcov coverage into coverage/ dir
        run: |
          export MWA_BEAM_FILE=$(realpath mwa_full_embedded_element_pattern.h5)
          cargo llvm-cov --workspace --lcov --output-path lcov.info

      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
