---
name: Tests

# Do this on every push
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    container: nvidia/cuda:11.1-base
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
          apt update -y
          DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
          apt install -y pkg-config curl git gcc llvm libclang-dev cuda-nvcc-11-1 libcfitsio-dev liberfa-dev

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Get the HDF5 file
      run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

    - name: Run tests
      run: |
        MWA_BEAM_FILE=mwa_full_embedded_element_pattern.h5 \
        HYPERDRIVE_CUDA_COMPUTE=75 \
        cargo test --all
